USE [PrestigeCars_Project3];
GO

CREATE TYPE Udt.SurrogateKeyInt
FROM INT NOT NULL;

CREATE TYPE Udt.PersonFirstName
FROM VARCHAR(50) NOT NULL;

CREATE TYPE Udt.PersonLastName
FROM VARCHAR(50) NOT NULL;

CREATE TYPE Udt.EmailAddress
FROM VARCHAR(255) NOT NULL;

CREATE TYPE Udt.PhoneNumber
FROM VARCHAR(20) NOT NULL;

CREATE TYPE Udt.AddressLine
FROM VARCHAR(100) NOT NULL;

CREATE TYPE Udt.CityName
FROM VARCHAR(50) NOT NULL;

CREATE TYPE Udt.PostalCode
FROM VARCHAR(15) NOT NULL;

CREATE TYPE Udt.PersonFullName
FROM VARCHAR(100) NOT NULL;

CREATE TYPE Udt.DepartmentName
FROM VARCHAR(50) NOT NULL;

CREATE TYPE Udt.HierarchyReference
FROM INT NULL;