USE [PrestigeCars_Project3];
GO

CREATE TYPE Udt.SalesRegionName
FROM VARCHAR(50) NOT NULL;

CREATE TYPE Udt.CountryName
FROM VARCHAR(100) NOT NULL;

CREATE TYPE Udt.ISO2
FROM CHAR(2) NOT NULL;

CREATE TYPE Udt.ISO3
FROM CHAR(3) NOT NULL;